### ISSUE TITLE
Mobile: Format map click popup

### ISSUE THREAD

**Issue by cjscheele** [WIStCart/BordnerCoastal#19]
Format the map click popup to be more narrow (perhaps less than about 320px so that iPhone 5 and like devices look good). We could also consider having the popup be docked to the top or bottom in mobile mode.

**Comment by scottsfarley93** [comment]
Should there be an overflow scroll bar? Or should the table reformat to be more vertical?

**Comment by cjscheele** [comment]
I think the latter would be best.
