### ISSUE TITLE
Opacity slider appears to be changing point opacity

### ISSUE THREAD

**Issue by codiesee** [WIStCart/BordnerCoastal#72]
Opacity slider appears to be changing point feature opacity as well as polygon. Appears to be context specific. Steps to duplicate: 
fresh map >  turn on points > turn down opacity slider > refresh map (using stateful URL) > points appear slightly transparent and are below the poly layer
*note that this may be the same issue as the existing z-level issue 
** This issue also applies to line features (same issue arises)

**Comment by cjscheele** [comment]
This is because the slider is attached to the point and line layer for some reason still. I think it is an artifact of the planned functionality of mutually exclusive layers. Lines 440-444 and 548-552

**Comment by cjscheele** [comment]
This doesn't appear to be a problem anymore.
